jmchor/activity_logger

models/Activity.model.js
The "date" key is now an Object full of Boolean Objects. every date is set to false, aka "date.isMonday" = false, unless we set it to true
=> Create Activity Model

middleware/routeguard.js, routes/auth.routes.js
- wrote the middleware and exported it.
- required it in the auth.routes
- did NOT add it to the routes yet
=> isLoggedIn Middleware

models/Activity.model.js
- made the basic model less verbose by using an array for the weekdays
- changed the model, so that it is possible to plan an activity for a specific day or have it recurring every week
- this got a bit complex, please check if the logic is right.
=> Updated activity model

models/Activity.model.js
- added isDone key
- changed 'specific' for 'once'
=> update activity model

app.js, routes/auth.routes.js, routes/index.routes.js, views/auth/login.hbs
- created new route "/home" because I couldn't create a logic where logged-out "/" shows the signup and login, and the logged-in "/" shows the main screen (the route doesn't seem to update the added middleware)
- Login POST route now takes in username and password, throws errors for wrong username and wrong password (compares hashes)
- Login POST route redirects to /home with a loggedin-layout (tested, works!)
=> Update login routes

models/Activity.model.js
Did not make the property "required"
=> Add category to activity model

public/stylesheets/style.css, views/auth/login.hbs, views/auth/sign-up.hbs, views/home.hbs, views/index.hbs, views/layout.hbs
Done:
- Included Bootstrap
- Imported fonts
- Basic CSS styling (in progress)
- Header and footer navigation links and styling
Still need to do:
- Burger menu for mobile view
- Icons for footer
Colours are subject to change. Haven't really thought about a colour palette yet.
=> Styled header and footer (WIP)

views/layout.hbs
Renamed the link to creating an activity in the layout from "new-activity" to "create" to match the route
=> Rename link to creating an activity

routes/activity.routes.js
Include function to convert days names (from the form) to numbers for the .getDay() function
Include logic for when only a specific date is picked
Include logic for when only one day is picked for repetition
Include logic for when multiple days are picked
Creates an individual activity for the general day with a specific date included for each repetition
Number of activities is limited until the end of the year. Minimum activity number is 1 (specific Date) or 366 (if created on January 1st for every weekday in a Leap year)
=> Updated create route to create multiple activities

public/stylesheets/style.css, views/layout.hbs
- Removed Google Fonts import for compliance
- Restructured header navigation to meet Bootstrap 5 standards
- Burger menu for mobile viewports works now
Colours, styling, transitions for later.
=> Burger menu created with Bootstrap 5

config/index.js, routes/activity.routes.js, views/day-info.hbs, views/partials/day.hbs, views/schedule.hbs
working weekly schedule
partial file made but not used
=> View schedule weekly

package-lock.json, package.json, public/stylesheets/style.css, views/layout.hbs
- Footer navigation has icons
- Buttons are evenly spaced
- Works fine on mobile view, spacing needs to be improved for tablet/desktop views
For later: Animate buttons and icons on hover
=> Bottom navbar

routes/activity.routes.js, views/edit-activity.hbs
This PR includes:
- View a single Activity in detail
- Edit the Activity right away (skipping a step of just viewing to view & edit, up for debate)
- Create GET route with edit form
- Create POST route that updates the Activity in the database
**PROBLEM**:
- Editing the date for a "once" activity does not work yet - there seems to be a problem with how the date is saved in the database (_YYYYMMDD_) and the format the date picker provides (_MMDDYYYY_) - causes a conflict and the activity is not updated. I commented out the code about editing the specific date for now until we have a solution
=> Code view activity detail routes

views/partials/day.hbs
**Merge this PR AFTER PR#43**
Include the link to the edit route in the new day partial
=> Include the path to edit route in day partial

app.js, package-lock.json, package.json, routes/activity.routes.js, views/edit-activity.hbs, views/layout.hbs, views/profile.hbs
Button in the edit view now deletes the entire activity
=> Delete Activity Route/View

public/stylesheets/style.css, views/layout.hbs, views/partials/day.hbs
- Improved layout and styling of hheader and footer navigations
- Small CSS fixes
=> Overall grid layout improvements

routes/activity.routes.js, views/profile.hbs
=> Edit req.user to req.session.currentUser

public/stylesheets/style.css, views/auth/login.hbs, views/auth/sign-up.hbs, views/create-activity.hbs, views/home.hbs, views/index.hbs, views/layout.hbs, views/partials/day.hbs, views/partials/randomfact.hbs, views/schedule.hbs
- Added basic styles for all views that are mostly done
Optimised for mobile viewports, so the Desktop version still looks a little jank. I want to complete the mobile styles first before I adjust for bigger viewports.
=> Basic main content layout/styling

public/stylesheets/style.css, views/auth/login.hbs, views/auth/sign-up.hbs, views/create-activity.hbs, views/edit-activity.hbs, views/home.hbs, views/index.hbs, views/layout.hbs, views/partials/day.hbs, views/partials/randomfact.hbs, views/schedule.hbs
I couldn't stand how bad the larger viewports looked, so I adjusted the grid for them, too.
Final tablet/desktop viewports need to differ a lot more by using different @media breakpoints. But for now, this is acceptable until the mobile layout is final.
=> Fundamental styles for larger viewports

routes/activity.routes.js, views/schedule.hbs
**CAUTION**
This PR adds the functionality to go forward and backward in the View Schedule view.
~~BUT~~ 
~~After showing week 12 and 13, week 14 is suddenly empty. The same is true for going backwards, randomly activities from much later dates will appear in week 8 or whatever.~~ 
~~So - it does work a bit, but it needs a lot of work~~ 
~~**THIS PR IS JUST FOR TESTING**~~ 
~~**DO NOT MERGE**~~
=> Add broken functionality to switch week views

routes/activity.routes.js, views/schedule.hbs
Reverts jmchor/activity_logger#57
=> Revert "Add broken functionality to switch week views"

models/User.model.js, routes/activity.routes.js, routes/auth.routes.js, views/auth/sign-up.hbs
I moved the profile-related routes to auth, since the bcryptjs-package was already required there. In my opinion, auth stuff belongs to the auth routes.
For some reason we seem to need an email, otherwise Mongoose will throw an error code 11000 all the time (something to do with duplicate keys. It works to have exactly ONE user without an email, but not two, so I required it.
Delete profile/user works now.
=> Delete profile route

config/session.config.js, routes/auth.routes.js, views/auth/login.hbs
Added "Remember Me" at Log in:
- default session cookie will expire after 30 Minutes
- Checking Remember Me at login will have the cookie last for 24 hours
Will now need update to login view (sorry ;))
=> Add functionality of Remember Me Login

README.md
=> README so far

views/create-activity.hbs
[Add task view]
- Replaced options selector with tabs
- Overall layout improvements
=> New activity tabs

package-lock.json, package.json, public/js/weekly-chart.js, routes/auth.routes.js, views/auth/statistics.hbs, views/layout.hbs
=> Created Charts

views/create-activity.hbs, views/edit-activity.hbs
- Added Categories to Add Task
- Added Categories to Edit Task
=> Category options

views/auth/statistics.hbs
When a day is empty of activities, no chart gets shown (but also nothing else
added the if-handlebar helpers as well as if-conditions to the chartjs script
=> Add conditions for empty days/weeks/months

public/stylesheets/style.css, views/create-activity.hbs, views/edit-activity.hbs
A style suggestion for the edit form
=> Add bootstrap styling to edit form

routes/auth.routes.js, routes/schedule.routes.js, views/partials/day.hbs, views/schedule.hbs
Unchecking an activity now sets it back to "isDone = false"
I also added the errorMessage on API - not-loading to the schedule view
=> Update activities on check/uncheck in week view

routes/auth.routes.js, views/auth/login.hbs, views/auth/reset-password.hbs, views/auth/update-password.hbs, views/profile.hbs
Realized that the Password Reset function actually did not work.
Now it does. I set up a route for resetting the password when logged out (known as "forgot password") as well as a route for updating the password from the logged-in user profile
While at it, I structured the auth routes a bit with Headline comments for better readability
=> Password update and reset working now

public/stylesheets/outstyle.css
Forgot to save my last changes to CSS and index.hbs, so just merging the missing things rn.
=> Index login signup design

views/auth/login.hbs
Small update for login title formatting
=> Updated login title again

public/stylesheets/outstyle.css, public/stylesheets/style.css
Thanks for picking up on this one!
It should be fixed for all viewports now. Doesn't work on Schedule view yet because it's not properly formatted, but should be good on all other views.
=> Scrolling issue fix
